name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn compile --batch-mode --errors --fail-at-end --show-version --no-transfer-progress -DinstallAtEnd=true -DdeployAtEnd=true -Dhttps.protocols=TLSv1.2 -Djava.awt.headless=true

    - name: Test with Maven
      run: mvn test --batch-mode --errors --fail-at-end --show-version --no-transfer-progress -DinstallAtEnd=true -DdeployAtEnd=true -Dhttps.protocols=TLSv1.2 -Djava.awt.headless=true

    - name: Deploy with Maven
      run: mvn install --batch-mode --errors --fail-at-end --show-version --no-transfer-progress -DinstallAtEnd=true -DdeployAtEnd=true -Dhttps.protocols=TLSv1.2 -Djava.awt.headless=true

    - name: Upload JAR artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packaged-jars
        path: target/*.jar
